version: '2'
services: 
    database:
        container_name: monaco-database
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=123456
            - MYSQL_USER=dev
            - MYSQL_PASSWORD=123456
            - MYSQL_DATABASE=catchup_monaco

    apache:
        container_name: monaco-web
        build: apache
        restart: always
        volumes:
            - ./monaco-telecom-replay-bo:/var/www
        links:
            - php
        environment:
            - VIRTUALHOST=public

    php:
        container_name: monaco-cgi
        build: php-fpm
        restart: always
        volumes:
            - ./monaco-telecom-replay-bo:/var/www
        ports:
            - 9000:9000
        links:
            - database
            - cache

    cache:
        container_name: monaco-memcached
        image: memcached

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: monaco-phpmyadmin
        restart: always
        links:
            - database
        environment:
            PMA_HOST: database
            PMA_USER: root
            PMA_PASSWORD: 123456

    
        
    #dockerUi:
        #image: dockerui/dockerui
        #restart: always
        #volumes:
            #- /var/run/docker.sock:/var/run/docker.sock
        #ports:
            #- 5000:9000
